export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';

export const HOTEL_CREATE_REQUEST = 'HOTEL_CREATE_REQUEST';
export const HOTEL_CREATE_SUCCESS = 'HOTEL_CREATE_SUCCESS';
export const HOTEL_CREATE_FAIL = 'HOTEL_CREATE_FAIL';
